#include <stdio.h>
#include "dictionary.h"

// Struct untuk dataset agar lebih rapi
typedef struct {
    const char* indonesian;
    const char* english;
    PartOfSpeech pos;
    const char* definition;
    const char* example;
    const char* pronunciation;
    WordCategory category;
} RawWordData;

// Memuat data kata awal ke dictionary
void dict_load_initial_data(DictionaryManager* dict) {
    if (dict == NULL) return;

    RawWordData initial_words[] = {
        // KATA SEHARI-HARI
        {"makan", "eat", VERB, "Memasukkan makanan ke dalam mulut", "I eat rice", "iit", EVERYDAY},
{"minum", "drink", VERB, "Meneguk air", "She drinks plain water", "drink", EVERYDAY},
{"buku", "book", NOUN, "Kumpulan kertas berisi tulisan", "I read a book", "buk", EVERYDAY},
{"besar", "big", ADJECTIVE, "Ukurannya lebih dari rata-rata", "The house is very big", "big", EVERYDAY},
{"kecil", "small", ADJECTIVE, "Ukurannya kurang dari rata-rata", "The cat is small", "smool", EVERYDAY},
{"cepat", "fast", ADJECTIVE, "Dalam waktu singkat", "The car drives fast", "fest", EVERYDAY},
{"saya", "I", PRONOUN, "Kata ganti orang pertama", "I go to the market", "ai", EVERYDAY},
{"di", "at", PREPOSITION, "Menunjukkan tempat", "He is at home", "et", EVERYDAY},
{"dan", "and", CONJUNCTION, "Menghubungkan dua unsur", "You and I", "end", EVERYDAY},
{"halo", "hello", INTERJECTION, "Kata sapaan", "Hello, how are you?", "he-lou", EVERYDAY},
{"tidur", "sleep", VERB, "Mengistirahatkan badan dan kesadaran", "He sleeps very soundly", "sliip", EVERYDAY},
{"air", "water", NOUN, "Cairan jernih yang dibutuhkan tubuh", "Please get me a glass of water", "wo-ter", EVERYDAY},
{"panas", "hot", ADJECTIVE, "Suhu yang tinggi", "This coffee is still very hot", "hot", EVERYDAY},
{"dingin", "cold", ADJECTIVE, "Suhu yang rendah", "The night air is quite cold", "kould", EVERYDAY},
{"kamu", "you", PRONOUN, "Kata ganti orang kedua", "Where do you want to go?", "yuu", EVERYDAY},
{"ke", "to", PREPOSITION, "Menandakan arah atau tujuan", "They go to school", "tuu", EVERYDAY},
{"atau", "or", CONJUNCTION, "Kata penghubung pilihan", "Choose tea or coffee?", "or", EVERYDAY},
{"hai", "hi", INTERJECTION, "Sapaan santai", "Hi, long time no see!", "hai", EVERYDAY},
{"hari", "day", NOUN, "Waktu dari pagi hingga malam", "The weather is sunny today", "dei", EVERYDAY},
{"jalan", "walk", VERB, "Melangkahkan kaki untuk berpindah", "We walk to the campus", "wok", EVERYDAY},
{"rumah", "house", NOUN, "Bangunan tempat tinggal manusia", "I go home after work", "haus", EVERYDAY},
{"mobil", "car", NOUN, "Kendaraan darat beroda empat", "He just bought a car", "kaar", EVERYDAY},
{"lari", "run", VERB, "Melangkah dengan kecepatan tinggi", "The child runs to chase the kite", "ran", EVERYDAY},
{"cantik", "beautiful", ADJECTIVE, "Elok atau menarik dipandang", "The view from the top of the hill is very beautiful", "byu-ti-ful", EVERYDAY},
{"dari", "from", PREPOSITION, "Menunjukkan tempat asal", "Our family comes from Medan", "from", EVERYDAY},
{"membaca", "read", VERB, "Melihat serta memahami isi tulisan", "I like to read technology articles", "riid", EVERYDAY},
{"merah", "red", ADJECTIVE, "Warna dasar yang menyerupai darah", "The red shirt looks eye-catching", "red", EVERYDAY},
{"besok", "tomorrow", NOUN, "Hari setelah hari ini", "This assignment must be submitted tomorrow", "tu-mo-rou", EVERYDAY},
{"pagi", "morning", NOUN, "Waktu pada awal hari", "Good morning everyone", "mor-ning", EVERYDAY},
{"malam", "night", NOUN, "Waktu setelah matahari terbenam", "Stars are clearly visible at night", "nait", EVERYDAY},
{"teman", "friend", NOUN, "Orang yang dikenal dan disukai", "She is my good friend", "frend", EVERYDAY},
{"keluarga", "family", NOUN, "Kelompok orang yang memiliki hubungan darah", "My family lives out of town", "fe-me-li", EVERYDAY},
{"uang", "money", NOUN, "Alat tukar yang sah", "I forgot to bring cash money", "ma-ni", EVERYDAY},
{"beli", "buy", VERB, "Memperoleh sesuatu dengan menukar uang", "We want to buy food", "bai", EVERYDAY},
{"meja", "table", NOUN, "Perabot dengan permukaan datar dan berkaki", "The book is on the table", "tei-bel", EVERYDAY},
{"kursi", "chair", NOUN, "Perabot untuk tempat duduk", "Please get one more chair", "cer", EVERYDAY},
{"kucing", "cat", NOUN, "Hewan peliharaan berkaki empat", "The cat is sleeping soundly", "ket", EVERYDAY},
{"anjing", "dog", NOUN, "Hewan yang sering dijadikan penjaga", "The neighbor's dog barked all night", "dog", EVERYDAY},
{"matahari", "sun", NOUN, "Pusat tata surya yang memancarkan cahaya", "The sun rises from the east", "san", EVERYDAY},
{"bulan", "moon", NOUN, "Satelit alami bumi", "The full moon looks very bright", "muun", EVERYDAY},
{"hitam", "black", ADJECTIVE, "Warna gelap paling pekat", "He wears a black shirt", "blek", EVERYDAY},
{"putih", "white", ADJECTIVE, "Warna dasar yang terang", "The paper is clean white", "wait", EVERYDAY},
{"atas", "above", PREPOSITION, "Posisi yang lebih tinggi", "The notebook is placed above the table", "e-baf", EVERYDAY},
{"bawah", "below", PREPOSITION, "Posisi yang lebih rendah", "The item fell below the table", "bi-lou", EVERYDAY},
{"belajar", "study", VERB, "Berusaha memperoleh kepandaian atau ilmu", "I am studying discrete mathematics", "sta-di", EVERYDAY},
{"tulis", "write", VERB, "Membuat huruf atau angka dengan pena", "Please write this function code on the board", "rait", EVERYDAY},
{"tugas", "assignment", NOUN, "Pekerjaan yang menjadi tanggung jawab", "The campus assignments are very heavy this week", "e-sain-men", EVERYDAY},
{"kuning", "yellow", ADJECTIVE, "Warna seperti emas atau pisang matang", "The cursor on the screen turns yellow", "ye-lou", EVERYDAY},
{"hijau", "green", ADJECTIVE, "Warna dasar yang menyerupai daun", "The success indicator will light up green", "griin", EVERYDAY},
{"kanan", "right", ADVERB, "Arah yang berlawanan dengan kiri", "Shift the button to the right side", "rait", EVERYDAY},
{"kiri", "left", ADVERB, "Arah yang berlawanan dengan kanan", "The navigation panel is on the left side of the screen", "left", EVERYDAY},
{"buka", "open", VERB, "Menjadikan sesuatu tidak tertutup", "Please open the text file", "ou-pen", EVERYDAY},
{"lagu", "song", NOUN, "Karya musik dengan lirik", "The song from Reality Club is very pleasant to hear", "song", EVERYDAY},
{"konser", "concert", NOUN, "Pertunjukan musik langsung", "Barasuara will hold a concert in this city", "kon-sert", EVERYDAY},
{"cinta", "love", NOUN, "Perasaan kasih sayang yang mendalam", "Her love is pure like a fairy", "laf", EVERYDAY},
{"rindu", "miss", VERB, "Keinginan kuat untuk bertemu", "I miss our casual chat last night", "mis", EVERYDAY},
{"tenggat", "deadline", NOUN, "Batas waktu akhir", "The campus assignment deadline is getting closer", "ded-lain", EVERYDAY},
{"ujian", "exam", NOUN, "Tes untuk mengukur kemampuan", "I hope I pass the calculus exam tomorrow", "eg-zem", EVERYDAY},
{"kampus", "campus", NOUN, "Area lingkungan perguruan tinggi", "The trip from home to campus was quite smooth", "kem-pes", EVERYDAY},
{"pulau", "island", NOUN, "Daratan yang dikelilingi air", "The natural scenery on Sibandang Island is fascinating", "ai-lend", EVERYDAY},
{"foto", "photo", NOUN, "Gambar yang dibuat dengan kamera", "I became a photography relator last week", "fou-tou", EVERYDAY},
{"sampah", "waste", NOUN, "Barang yang tidak berguna lagi", "We need to start cleaning up digital waste", "weist", EVERYDAY},
{"bersih", "clean", ADJECTIVE, "Bebas dari kotoran", "This browser extension makes email cleaner", "kliin", EVERYDAY},
{"bintang", "star", NOUN, "Benda langit yang memancarkan cahaya", "The star tonight looks very bright", "staar", EVERYDAY},
{"langit", "sky", NOUN, "Ruang di atas bumi", "The evening sky turns orange", "skai", EVERYDAY},
{"angin", "wind", NOUN, "Udara yang bergerak", "The beach wind blows quite hard", "wind", EVERYDAY},
{"kopi", "coffee", NOUN, "Minuman hasil seduhan biji kopi", "A cup of coffee accompanies tonight's coding session", "ko-fi", EVERYDAY},
{"teh", "tea", NOUN, "Minuman dari seduhan daun teh", "She prefers to drink warm tea", "tii", EVERYDAY},
{"gula", "sugar", NOUN, "Bahan pemanis", "Please add a little sugar to this drink", "syu-ger", EVERYDAY},
{"pintu", "door", NOUN, "Jalan masuk atau keluar", "Please close the door after entering", "door", EVERYDAY},
{"jendela", "window", NOUN, "Lubang masuknya cahaya dan udara", "Open the window so fresh air can come in", "win-dou", EVERYDAY},
{"kamar", "room", NOUN, "Ruang yang bersekat dinding", "I spend my free time in the room", "ruum", EVERYDAY},
{"ayam", "chicken", NOUN, "Unggas yang biasa dipelihara untuk dimakan", "The fried chicken tastes very crispy", "ci-ken", EVERYDAY},
{"ikan", "fish", NOUN, "Hewan vertebrata yang hidup di air", "He keeps ornamental fish in an aquarium", "fisy", EVERYDAY},
{"pohon", "tree", NOUN, "Tumbuhan berkayu dengan batang utama", "The mango tree in the yard has borne fruit", "trii", EVERYDAY},
{"bunga", "flower", NOUN, "Bagian tumbuhan yang akan menjadi buah", "The rose flower smells so sweet", "flau-wer", EVERYDAY},
{"sepatu", "shoes", NOUN, "Alas kaki yang menutupi bagian kaki", "These new shoes are very comfortable to walk in", "syuuz", EVERYDAY},
{"baju", "shirt", NOUN, "Pakaian penutup badan", "The black shirt suits him very well", "syert", EVERYDAY},
{"celana", "pants", NOUN, "Pakaian bagian bawah tubuh", "These jeans pants have started to fade in color", "pents", EVERYDAY},
{"topi", "hat", NOUN, "Penutup kepala", "Use a hat so you don't get overheated", "het", EVERYDAY},
{"kacamata", "glasses", NOUN, "Lensa pada bingkai untuk membantu penglihatan", "Anti-radiation glasses are very useful when coding", "gla-siz", EVERYDAY},
{"tas", "bag", NOUN, "Wadah untuk menyimpan barang", "Don't forget to bring your backpack bag", "beg", EVERYDAY},
{"pensil", "pencil", NOUN, "Alat tulis berupa kayu berisi arang", "Please lend me a pencil for drawing", "pen-sil", EVERYDAY},
{"pulpen", "pen", NOUN, "Alat tulis dengan tinta", "This pen has run out of ink", "pen", EVERYDAY},
{"kertas", "paper", NOUN, "Lembaran untuk ditulisi", "Write your idea on a piece of paper", "pei-per", EVERYDAY},
{"dinding", "wall", NOUN, "Pemisah atau penutup ruangan", "The room wall is painted white", "wol", EVERYDAY},
{"lantai", "floor", NOUN, "Permukaan bawah dari ruangan", "The dirty floor has just been swept", "floor", EVERYDAY},
{"atap", "roof", NOUN, "Penutup bagian atas bangunan", "Heavy rain caused the roof to leak", "ruuf", EVERYDAY},
{"rambut", "hair", NOUN, "Yang tumbuh di kulit kepala", "Her hair was cut very short", "her", EVERYDAY},
{"mata", "eye", NOUN, "Indra penglihatan", "Eyes get tired if looking at the screen for too long", "ai", EVERYDAY},
{"hidung", "nose", NOUN, "Indra penciuman", "His nose is blocked due to the flu", "nouz", EVERYDAY},
{"mulut", "mouth", NOUN, "Rongga untuk berbicara dan makan", "Please close your mouth when chewing", "mauth", EVERYDAY},
{"telinga", "ear", NOUN, "Indra pendengaran", "Put the earphones in your ear to listen to music", "iyer", EVERYDAY},
{"tangan", "hand", NOUN, "Anggota badan dari siku sampai ujung jari", "Wash your hands before eating", "hend", EVERYDAY},
{"kaki", "foot", NOUN, "Anggota badan untuk berjalan", "My feet are sore after walking far", "fut", EVERYDAY},
{"kepala", "head", NOUN, "Bagian tubuh bagian atas", "My head feels a bit dizzy today", "hed", EVERYDAY},
{"perut", "stomach", NOUN, "Bagian tubuh tempat pencernaan makanan", "The stomach feels hungry towards noon", "sta-mek", EVERYDAY},
{"masak", "cook", VERB, "Menyiapkan makanan dengan pemanasan", "Mother is cooking fried rice in the kitchen", "kuk", EVERYDAY},
{"sapu", "broom", NOUN, "Alat untuk membersihkan debu", "Please get the broom in the corner of the room", "bruum", EVERYDAY},
{"cuci", "wash", VERB, "Membersihkan dengan air", "Don't forget to wash your hands with soap", "wosy", EVERYDAY},
{"piring", "plate", NOUN, "Wadah pipih untuk tempat makan", "Put the side dish on the plate", "pleit", EVERYDAY},
{"gelas", "glass", NOUN, "Wadah berbentuk tabung untuk minum", "He broke a glass container", "glaas", EVERYDAY},
{"sendok", "spoon", NOUN, "Alat makan berbentuk cekung", "Eating soup is easier using a spoon", "spuun", EVERYDAY},
{"garpu", "fork", NOUN, "Alat makan dengan ujung bercabang", "Hold the fork in your left hand", "fork", EVERYDAY},
{"pisau", "knife", NOUN, "Alat tajam untuk memotong", "This kitchen knife needs to be sharpened", "naif", EVERYDAY},
{"bantal", "pillow", NOUN, "Alas kepala saat tidur", "This pillow is very soft and comfortable", "pi-lou", EVERYDAY},
{"selimut", "blanket", NOUN, "Kain pelindung tubuh dari hawa dingin", "The weather is very cold, I need a blanket", "bleng-kit", EVERYDAY},

        // KATA FORMAL
        {"kebijakan", "policy", NOUN, "Rangkaian konsep dan asas", "The government policy was changed", "po-li-si", FORMAL},
{"mengimplementasikan", "implement", VERB, "Menerapkan sesuatu", "We implement the new system", "im-ple-ment", FORMAL},
{"signifikan", "significant", ADJECTIVE, "Penting atau berarti", "There is a significant change", "sig-ni-fi-ken", FORMAL},
{"berkenaan", "regarding", PREPOSITION, "Berhubungan dengan", "The letter is regarding tomorrow's meeting", "ri-gar-ding", FORMAL},
{"klarifikasi", "clarification", NOUN, "Penjelasan lebih lanjut", "We need a clarification immediately", "kle-ri-fi-kei-syen", FORMAL},
{"mengevaluasi", "evaluate", VERB, "Menilai atau meninjau sesuatu", "The manager evaluates the team's performance", "i-vel-yu-eit", FORMAL},
{"komprehensif", "comprehensive", ADJECTIVE, "Lengkap dan menyeluruh", "The report is very comprehensive", "kom-pre-hen-sif", FORMAL},
{"partisipasi", "participation", NOUN, "Keterlibatan dalam suatu kegiatan", "Thank you for your participation", "par-ti-si-pei-syen", FORMAL},
{"kewajiban", "obligation", NOUN, "Sesuatu yang harus dilaksanakan", "Paying taxes is a citizen's obligation", "ob-li-gei-syen", FORMAL},
{"verifikasi", "verification", NOUN, "Pemeriksaan tentang kebenaran", "The data verification process is complete", "ve-ri-fi-kei-syen", FORMAL},
{"prosedur", "procedure", NOUN, "Tahapan kegiatan untuk menyelesaikan aktivitas", "Please follow the applicable procedure", "pru-si-jer", FORMAL},
{"mengalokasikan", "allocate", VERB, "Menentukan jatah untuk suatu tujuan", "The system allocates memory dynamically", "e-lo-keit", FORMAL},
{"substansial", "substantial", ADJECTIVE, "Bersifat inti atau memiliki dampak besar", "There is a substantial difference in this design", "seb-sten-syal", FORMAL},
{"indikator", "indicator", NOUN, "Sesuatu yang dapat menjadi petunjuk atau ukuran", "Access speed is a key performance indicator", "in-di-kei-ter", FORMAL},
{"merevisi", "revise", VERB, "Memperbaiki atau meninjau kembali", "We need to revise this search function", "ri-vais", FORMAL},
{"otoritas", "authority", NOUN, "Hak untuk bertindak atau memberi perintah", "Only the admin has that authority", "o-tho-ri-ti", FORMAL},
{"regulasi", "regulation", NOUN, "Aturan yang mengendalikan suatu sistem", "The company must comply with the new regulation", "re-gyu-lei-syen", FORMAL},
{"validasi", "validation", NOUN, "Pengesahan atau pengujian kebenaran", "The system is performing data validation", "ve-li-dei-syen", FORMAL},
{"negosiasi", "negotiation", NOUN, "Proses tawar-menawar untuk mencapai kesepakatan", "The negotiation process went smoothly", "ne-gou-syei-syen", FORMAL},
{"kompetensi", "competence", NOUN, "Kecakapan atau kemampuan", "Employees are assessed based on their competence", "kom-pe-tens", FORMAL},
{"fasilitas", "facility", NOUN, "Sarana untuk melancarkan fungsi", "This campus has complete facilities", "fe-si-li-ti", FORMAL},
{"domisili", "domicile", NOUN, "Tempat kediaman yang sah", "Please fill in your current domicile address", "do-mi-sail", FORMAL},
{"konfigurasi", "configuration", NOUN, "Pengaturan susunan atau bentuk", "The system network configuration needs to be updated", "ken-fi-gyu-rei-syen", FORMAL},
{"optimal", "optimal", ADJECTIVE, "Kondisi terbaik atau paling menguntungkan", "The application performance has reached an optimal level", "op-ti-mel", FORMAL},
{"integrasi", "integration", NOUN, "Penyatuan menjadi kesatuan yang utuh", "The integration between modules ran successfully", "in-te-grei-syen", FORMAL},
{"kapasitas", "capacity", NOUN, "Daya tampung maksimum", "The capacity of this room is full", "ke-pe-si-ti", FORMAL},
{"mekanisme", "mechanism", NOUN, "Cara kerja suatu alat atau sistem", "The data security mechanism is tightened", "me-ke-ni-zem", FORMAL},
{"struktural", "structural", ADJECTIVE, "Berkaitan dengan struktur atau susunan", "There is a slight structural change in the codebase", "strak-ce-rel", FORMAL},
{"representasi", "representation", NOUN, "Perbuatan atau hal mewakili sesuatu", "This graph is a representation of the data", "re-pre-zen-tei-syen", FORMAL},
{"dimensi", "dimension", NOUN, "Ukuran panjang, lebar, atau ruang", "The matrix has two dimensions", "dai-men-syen", FORMAL},
{"kalkulasi", "calculation", NOUN, "Perhitungan matematis", "The limit value calculation has finished executing", "kel-kyu-lei-syen", FORMAL},
{"alokasi", "allocation", NOUN, "Penentuan banyaknya barang atau tempat", "The memory allocation was successfully performed", "e-lo-kei-syen", FORMAL},
{"probabilitas", "probability", NOUN, "Kemungkinan terjadinya suatu peristiwa", "The probability of an error occurring is very small", "pro-be-bi-li-ti", FORMAL},
{"implementasi", "implementation", NOUN, "Pelaksanaan atau penerapan", "The linked list implementation has run smoothly", "im-ple-men-tei-syen", FORMAL},
{"ekstensi", "extension", NOUN, "Program tambahan untuk peramban", "This extension was made to support climate action", "ek-sten-syen", FORMAL},
{"relasi", "relation", NOUN, "Hubungan antar entitas", "The relation between data structures in C is connected", "ri-lei-syen", FORMAL},
{"kuantor", "quantifier", NOUN, "Simbol logika penunjuk jumlah", "An existential quantifier is used in this proof", "kwon-ti-fai-er", FORMAL},
{"sukarelawan", "volunteer", NOUN, "Orang yang melakukan sesuatu tanpa paksaan", "The registration for the economic event volunteer is closed", "vo-len-tiyer", FORMAL},
{"praktikum", "practicum", NOUN, "Pelajaran praktik di laboratorium", "The practicum report for human-computer interaction", "prek-ti-kem", FORMAL},
{"bank", "bank", NOUN, "Lembaga keuangan", "The bank account management project is being developed", "bengk", FORMAL},
{"iklim", "climate", NOUN, "Kondisi cuaca rata-rata", "Climate change is an urgent global issue", "klai-met", FORMAL},
{"akumulasi", "accumulation", NOUN, "Pengumpulan atau penghimpunan", "An error accumulation occurred during that iteration", "e-kyu-myu-lei-syen", FORMAL},
{"deduksi", "deduction", NOUN, "Penarikan kesimpulan dari keadaan umum", "The deduction method is used in mathematical proofs", "di-dak-syen", FORMAL},
{"induksi", "induction", NOUN, "Penarikan kesimpulan dari keadaan khusus", "Use mathematical induction to prove this series", "in-dak-syen", FORMAL},
{"konjungsi", "conjunction", NOUN, "Penghubung logika AND", "The conjunction value is true only if both are true", "ken-jengk-syen", FORMAL},
{"disjungsi", "disjunction", NOUN, "Penghubung logika OR", "This disjunction statement evaluates to false", "dis-jengk-syen", FORMAL},
{"implikasi", "implication", NOUN, "Keterlibatan atau keadaan sebab-akibat", "The logical implication of the statement is very clear", "im-pli-kei-syen", FORMAL},
{"ekuivalensi", "equivalence", NOUN, "Keadaan sebanding atau sama nilainya", "There is an equivalence between the two formulas", "i-kwi-ve-lens", FORMAL},
{"hipotesis", "hypothesis", NOUN, "Anggapan dasar yang masih harus dibuktikan", "This hypothesis needs further testing", "hai-poth-e-sis", FORMAL},
{"teorema", "theorem", NOUN, "Pernyataan yang dapat dibuktikan kebenarannya", "The central limit theorem is applied in this analysis", "thi-e-rem", FORMAL},
{"vektor", "vector", NOUN, "Besaran yang memiliki arah", "The cross product between vectors produces a new matrix", "vek-ter", FORMAL},
{"skalar", "scalar", NOUN, "Besaran yang hanya memiliki nilai", "The scalar is multiplied directly by the matrix elements", "skei-ler", FORMAL},
{"determinan", "determinant", NOUN, "Nilai khusus dari matriks persegi", "The determinant of this matrix is zero", "di-ter-mi-nent", FORMAL},
{"invers", "inverse", NOUN, "Kebalikan dari suatu fungsi atau matriks", "The matrix does not have an inverse", "in-vers", FORMAL},
{"otorisasi", "authorization", NOUN, "Pemberian kekuasaan atau hak", "User authorization was denied by the server", "o-the-ri-zei-syen", FORMAL},
{"administrasi", "administration", NOUN, "Usaha dan kegiatan tata usaha", "The administration department is processing your document", "ed-mi-nis-trei-syen", FORMAL},
{"birokrasi", "bureaucracy", NOUN, "Sistem pemerintahan yang dijalankan pegawai", "The campus bureaucracy is sometimes quite complicated", "byu-rok-re-si", FORMAL},
{"delegasi", "delegation", NOUN, "Pelimpahan wewenang", "This task has been handed over to the team delegation", "de-le-gei-syen", FORMAL},
{"efisiensi", "efficiency", NOUN, "Ketepatan cara atau usaha", "Memory efficiency is very important in C", "i-fi-syen-si", FORMAL},
{"efektivitas", "effectiveness", NOUN, "Keberhasilan mencapai tujuan", "The effectiveness of this method needs to be reviewed", "i-fek-tiv-nes", FORMAL},
{"fondasi", "foundation", NOUN, "Dasar atau landasan", "Discrete mathematics is the foundation of computer science", "faun-dei-syen", FORMAL},
{"formulasi", "formulation", NOUN, "Perumusan atau penyusunan", "The algorithm formulation took a week", "for-myu-lei-syen", FORMAL},
{"gradasi", "gradation", NOUN, "Perubahan warna secara berangsur-angsur", "The gradation effect on the interface is very smooth", "grei-dei-syen", FORMAL},
{"harmoni", "harmony", NOUN, "Kesesuaian atau keselarasan", "The color palette selection creates visual harmony", "haar-me-ni", FORMAL},
{"identifikasi", "identification", NOUN, "Penentu atau penetapan identitas", "The error identification process requires patience", "ai-den-ti-fi-kei-syen", FORMAL},
{"justifikasi", "justification", NOUN, "Alasan yang mengesahkan sebuah tindakan", "Provide a justification for using this data structure", "jas-ti-fi-kei-syen", FORMAL},
{"klasifikasi", "classification", NOUN, "Penyusunan bersistem dalam kelas atau golongan", "This data needs to be put into a technical classification", "kle-si-fi-kei-syen", FORMAL},
{"korelasi", "correlation", NOUN, "Hubungan timbal balik", "There is a correlation between system performance and latency", "ko-re-lei-syen", FORMAL},
{"legislasi", "legislation", NOUN, "Proses pembuatan undang-undang", "The legislation related to cybersecurity was recently passed", "le-jis-lei-syen", FORMAL},
{"mayoritas", "majority", NOUN, "Jumlah terbanyak dari suatu kelompok", "The majority of users like the new layout design", "me-jo-ri-ti", FORMAL},
{"minoritas", "minority", NOUN, "Golongan dengan jumlah lebih kecil", "Only a minority experienced errors in the application", "mai-no-ri-ti", FORMAL},
{"nominasi", "nomination", NOUN, "Pengusulan atau pengangkatan sebagai calon", "The browser extension project entered the campus nomination", "no-mi-nei-syen", FORMAL},
{"observasi", "observation", NOUN, "Peninjauan secara cermat", "From the observation results, this sorting method is slow", "ob-zer-vei-syen", FORMAL},
{"orientasi", "orientation", NOUN, "Peninjauan untuk menentukan sikap", "The orientation program for fresh graduate students starts today", "o-ri-en-tei-syen", FORMAL},
{"persepsi", "perception", NOUN, "Tanggapan atau penerimaan secara langsung", "The user perception of the application is very positive", "per-sep-syen", FORMAL},
{"presisi", "precision", NOUN, "Ketepatan atau ketelitian", "The double precision data type has a high precision", "pri-si-jyen", FORMAL},
{"proporsi", "proportion", NOUN, "Perbandingan atau perimbangan", "The layout proportion of the interface elements is just right", "pre-por-syen", FORMAL},
{"rasional", "rational", ADJECTIVE, "Menurut pikiran dan pertimbangan yang logis", "Choosing a binary tree structure is a rational decision", "re-sye-nel", FORMAL},
{"referensi", "reference", NOUN, "Sumber acuan atau rujukan", "The pointer will store the reference of the allocated memory", "re-fe-rens", FORMAL},
{"asumsi", "assumption", NOUN, "Ddugaan yang diterima sebagai dasar", "Our initial assumption turned out to be wrong", "e-samp-syen", FORMAL},
{"kontribusi", "contribution", NOUN, "Sumbangsih atau peran serta", "Thank you for your contribution to this project", "kon-tri-byu-syen", FORMAL},
{"aliansi", "alliance", NOUN, "Ikatan atau hubungan perserikatan", "Both companies formed a strategic alliance", "e-lai-ens", FORMAL},
{"konvensi", "convention", NOUN, "Aturan yang didasarkan pada kebiasaan", "The variable naming convention in C must be consistent", "ken-ven-syen", FORMAL},
{"fluktuasi", "fluctuation", NOUN, "Keadaan turun-naik", "The server latency fluctuation deeply affects performance", "flak-cu-ei-syen", FORMAL},
{"inspeksi", "inspection", NOUN, "Pemeriksaan secara saksama", "The security team conducted an inspection of the system", "in-spek-syen", FORMAL},
{"mitigasi", "mitigation", NOUN, "Upaya mengurangi risiko", "The system vulnerability mitigation must be executed immediately", "mi-ti-gei-syen", FORMAL},
{"paradigma", "paradigm", NOUN, "Kerangka berpikir atau model", "The structural programming paradigm is different from OOP", "pe-re-daim", FORMAL},
{"kriteria", "criterion", NOUN, "Ukuran yang menjadi dasar penilaian", "This application has met the test pass criterion", "krai-ti-ri-en", FORMAL},
{"substitusi", "substitution", NOUN, "Penggantian dengan hal lain", "Perform a value substitution on that variable", "sab-sti-tyu-syen", FORMAL},

        // KATA SLANG
        {"nongkrong", "hangout", VERB, "Berkumpul dan bersantai bersama teman", "Let's hangout at the cafe", "heng-aut", SLANG},
{"keren", "cool", ADJECTIVE, "Tampak bergaya atau bagus", "Your shoes are so cool", "kuul", SLANG},
{"gue", "I", PRONOUN, "Kata ganti orang pertama (kasar/akrab)", "I want to go home", "ai", SLANG},
{"banget", "very", ADVERB, "Sangat", "The food is very delicious", "ve-ri", SLANG},
{"mager", "lazy", ADJECTIVE, "Malas bergerak atau melakukan sesuatu", "It's raining today, so I'm too lazy to go out", "lei-zi", SLANG},
{"baper", "emotional", ADJECTIVE, "Terlalu membawa perasaan", "Don't get emotional, it's just a joke", "i-mou-syen-el", SLANG},
{"kuy", "let's go", INTERJECTION, "Ajakan santai untuk pergi", "Let's go, we are leaving now!", "lets-gou", SLANG},
{"mantul", "awesome", ADJECTIVE, "Sangat bagus atau memuaskan", "This interface design is so awesome!", "oo-sem", SLANG},
{"kepo", "curious", ADJECTIVE, "Terlalu ingin tahu urusan orang lain", "You don't need to be so curious", "kyu-ri-es", SLANG},
{"cuy", "bro", NOUN, "Panggilan akrab untuk teman", "Are you busy coding, bro?", "brou", SLANG},
{"gabut", "bored", ADJECTIVE, "Perasaan bosan karena tidak ada aktivitas", "I'm so bored, let's play together!", "boord", SLANG},
{"santuy", "relax", ADJECTIVE, "Bentuk tidak baku dari santai", "Just relax while doing the assignment", "ri-leks", SLANG},
{"healing", "healing", VERB, "Jalan-jalan atau liburan untuk melepas penat", "This weekend is our time for healing", "hii-ling", SLANG},
{"julid", "snarky", ADJECTIVE, "Suka berkomentar negatif terhadap orang lain", "No need to be so snarky about other people's work", "snar-ki", SLANG},
{"bestie", "bestie", NOUN, "Panggilan akrab untuk sahabat", "This afternoon I want to hang out with my bestie", "bes-ti", SLANG},
{"garing", "unfunny", ADJECTIVE, "Lelucon atau suasana yang tidak lucu", "Your joke tonight is so unfunny", "an-fa-ni", SLANG},
{"receh", "cheap/trivial", ADJECTIVE, "Lelucon atau hal yang sederhana namun menghibur", "Your sense of humor is so trivial", "ciip / tri-vi-el", SLANG},
{"pansos", "social climbing", VERB, "Mencari perhatian di media sosial", "She creates drama just for social climbing", "sou-syel klai-ming", SLANG},
{"bucin", "whipped/slave to love", ADJECTIVE, "Budak cinta, terlalu rela berkorban demi pasangan", "Since they started dating, he has been so whipped", "wipt / sleiv-tu-laf", SLANG},
{"mabar", "play together", VERB, "Main bareng, biasanya untuk game online", "Let's play together tonight", "plei tu-ge-der", SLANG},
{"woles", "slow down/chill", ADJECTIVE, "Santai, dari kata selow yang dibalik", "Just chill, the deadline is still far away", "slou-daun / cil", SLANG},
{"lebay", "overreacting", ADJECTIVE, "Bereaksi terlalu berlebihan", "Her startled reaction was totally overreacting", "ou-ver-ri-ek-ting", SLANG},
{"ngelag", "lagging", ADJECTIVE, "Kondisi tersendat saat menggunakan komputer", "The internet is bad, my game is lagging so hard", "le-ging", SLANG},
{"cupu", "noob", ADJECTIVE, "Kurang mahir atau pemula", "Your gameplay is still such a noob, you need more practice", "nuub", SLANG},
{"sabi", "can do/cool", ADJECTIVE, "Bisa atau sanggup", "This layout design idea is cool enough to try", "ken-duu / kuul", SLANG},
{"otewe", "on the way", ADVERB, "Sedang dalam perjalanan", "Wait a minute, I'm already on the way to the location", "on-de-wei", SLANG},
{"gamon", "fail to move on", VERB, "Gagal melupakan kenangan masa lalu", "It's been a long time but he still fails to move on", "feil-tu-muuv-on", SLANG},
{"kicep", "speechless", ADJECTIVE, "Terdiam karena takut atau tidak bisa menjawab", "He was immediately speechless when asked about the error code", "spiic-les", SLANG},
{"afk", "away from keyboard", ADJECTIVE, "Meninggalkan permainan atau komputer sejenak", "Don't go away from keyboard while the round is ongoing!", "e-wei-frem-ki-bord", SLANG},
{"gg", "good game", INTERJECTION, "Pujian untuk permainan yang bagus", "Such an exciting match tonight, good game!", "gud-geim", SLANG},
{"sepuh", "expert", NOUN, "Orang yang sangat berpengalaman atau jago", "Wow, the coding expert has stepped in", "ek-spert", SLANG},
{"ngebug", "glitching", VERB, "Terjadi kesalahan sistem atau cacat visual", "The character in my game is glitching through the wall", "gli-cing", SLANG},
{"toxic", "toxic", ADJECTIVE, "Perilaku merugikan atau berkata kasar", "Please keep your etiquette, don't be a toxic player", "tok-sik", SLANG},
{"ngeheal", "healing", VERB, "Memulihkan darah atau nyawa dalam game", "Help healing me, my HP is running low", "hii-ling", SLANG},
{"gacor", "awesome/lucky", ADJECTIVE, "Sangat hebat atau sedang beruntung", "His weapon is so awesome for playing ranked matches", "oo-sem / la-ki", SLANG},
{"kode", "code", NOUN, "Isyarat atau sandi penukaran", "There is a new redeem code for Heartopia game", "koud", SLANG},
{"senggol", "challenge me", VERB, "Menantang atau memamerkan pencapaian", "Challenge me if you can, my Roblox profile has been updated", "ce-lenj-mii", SLANG},
{"kinyis", "fresh", ADJECTIVE, "Sangat baru atau segar", "The UI appearance still looks so fresh", "fresy", SLANG},
{"anjay", "wow", INTERJECTION, "Ekspresi kekaguman santai", "Wow, the web transition animation is so smooth", "wau", SLANG},
{"cuan", "profit", NOUN, "Keuntungan uang", "If this extension project is released, it can bring a profit", "pro-fit", SLANG},
{"kudet", "outdated", ADJECTIVE, "Kurang update atau tertinggal informasi", "Don't be outdated, this framework is already using the new version", "aut-dei-ted", SLANG},
{"ansos", "antisocial", ADJECTIVE, "Anti sosial, jarang bergaul", "Get out of your room once in a while, don't be antisocial", "en-ti-sou-syel", SLANG},
{"gercep", "fast response", VERB, "Gerak cepat dalam merespons sesuatu", "He always gives a fast response when asked to fix bugs", "fest-ri-spons", SLANG},
{"mantan", "ex", NOUN, "Orang yang pernah menjalin hubungan asmara", "He accidentally met his ex at the cafe", "eks", SLANG},
{"gebetan", "crush", NOUN, "Orang yang sedang disukai atau ditaksir", "Finally, he gathered the courage to reply to his crush's chat", "krasy", SLANG},
{"galau", "upset", ADJECTIVE, "Perasaan bimbang, sedih, atau kecewa", "Don't stay upset just because of an error code", "ap-set", SLANG},
{"alay", "tacky", ADJECTIVE, "Gaya yang dianggap berlebihan atau norak", "The design style with that color gradient feels so tacky", "te-ki", SLANG},
{"fyp", "for your page", NOUN, "Masuk ke beranda utama atau viral", "Hopefully this C language tutorial video gets on the for your page", "for-yor-peij", SLANG},
{"spill", "reveal", VERB, "Membocorkan rahasia atau informasi", "Try to reveal how to make a good glassmorphism effect", "ri-viil", SLANG},
{"fomo", "fear of missing out", ADJECTIVE, "Takut ketinggalan tren", "Don't buy an expensive game just because of the fear of missing out", "fiyer-of-mi-sing-aut", SLANG},
{"sirkel", "circle", NOUN, "Lingkungan pertemanan", "His hangout circle consists entirely of programmers", "ser-kel", SLANG},
{"salting", "blushing", VERB, "Salah tingkah karena malu atau gugup", "She was immediately blushing when praised by her crush", "bla-sying", SLANG},
{"roasting", "roast", VERB, "Menyindir atau mengejek dengan gaya komedi", "Don't get angry easily when you are getting a roast", "roust", SLANG},
{"ngab", "bro", NOUN, "Panggilan akrab antar pria", "Are you busy with assignments tonight, bro?", "brou", SLANG},
{"japri", "private message", VERB, "Jalur pribadi atau chat langsung", "If you have further questions, just send a private message", "prai-vet me-sej", SLANG},
{"gaje", "unclear", ADJECTIVE, "Gak jelas, aneh, atau tidak masuk akal", "The way that person talks is so unclear today", "an-kliyer", SLANG},
{"brb", "be right back", INTERJECTION, "Akan segera kembali", "Hold on, I want to get a drink, be right back", "bii-rait-bek", SLANG},
{"bocil", "kid", NOUN, "Bocah cilik atau anak kecil", "There are many kids playing games at the internet cafe across the street", "kid", SLANG},
{"caper", "attention seeker", ADJECTIVE, "Cari perhatian orang lain", "His behavior on social media looks like an attention seeker", "e-ten-syen sii-ker", SLANG},
{"doi", "crush/partner", NOUN, "Panggilan untuk pacar atau orang yang disukai", "Yesterday I saw my partner walking alone", "krasy / part-ner", SLANG},
{"insecure", "insecure", ADJECTIVE, "Perasaan tidak aman atau tidak percaya diri", "Looking at the design expert's work makes me feel insecure", "in-se-kyur", SLANG},
{"nolep", "no life", ADJECTIVE, "Tidak memiliki kehidupan sosial di luar rumah", "Because of the assignment deadlines, I have no life this week", "nou-laif", SLANG},
{"mantab", "great", ADJECTIVE, "Sangat memuaskan", "Dinner tonight was absolutely great!", "greit", SLANG},
{"sambat", "complain", VERB, "Mengeluh tanpa henti", "The new task has just started, why do you keep complaining", "kem-plein", SLANG},
{"valid", "true", ADJECTIVE, "Sesuai fakta", "What you just said is so true, I agree", "truu", SLANG},
{"savage", "ruthless", ADJECTIVE, "Keren dan tak kenal ampun dalam ucapan", "Her chat reply just now was truly ruthless", "ruth-les", SLANG},
{"relate", "relatable", ADJECTIVE, "Bisa dihubungkan dengan pengalaman pribadi", "This meme about coding revision is so relatable", "ri-lei-te-bel", SLANG},
{"tengil", "arrogant", ADJECTIVE, "Sikap menyebalkan atau gaya sok", "His play style in Valorant is so arrogant", "e-ro-gent", SLANG},
{"pargoy", "party dance", VERB, "Joget atau tari khas anak muda", "This song is really fun to be used for a party dance", "par-ti dens", SLANG},
{"ngopi", "chill/coffee", VERB, "Istirahatsantai sambil minum kopi", "My mind is stuck, let's just chill with some coffee first", "cil / ko-fi", SLANG},
{"mleyot", "flustered", ADJECTIVE, "Kondisi tidak kuat menahan rasa gemas", "Watching their interaction makes me feel so flustered", "flas-terd", SLANG},
{"gemoy", "cute", ADJECTIVE, "Sangat menggemaskan", "The neighbor's cat has such a cute body", "kyuut", SLANG},
{"ngabrut", "laugh out loud", VERB, "Tertawa terbahak-bahak", "The joke from the UI/UX guy made me laugh out loud", "laf-aut-laud", SLANG},
{"starboy", "cool guy", NOUN, "Pria yang karismatik dan bergaya keren", "He dressed up so neatly today, looking like a cool guy", "kuul gai", SLANG},
{"redflag", "toxic trait", NOUN, "Tanda bahaya atau sifat buruk seseorang", "Interrupting conversations often is such a toxic trait", "tok-sik treit", SLANG},
{"greenflag", "good trait", NOUN, "Tanda positif atau sifat baik", "She is always on time, that's such a good trait", "gud treit", SLANG},
{"fiks", "certain/fixed", ADJECTIVE, "Sudah pasti atau tidak bisa diganggu gugat", "This interface design is already fixed, we just need to implement it", "ser-ten / fikst", SLANG},

        // KATA TEKNIS
        {"algoritma", "algorithm", NOUN, "Prosedur langkah-demi-langkah", "The data search algorithm is efficient", "al-go-ri-them", TECHNICAL},
{"memori", "memory", NOUN, "Kapasitas penyimpanan data", "The computer memory is full", "me-me-ri", TECHNICAL},
{"enkripsi", "encryption", NOUN, "Proses mengamankan informasi", "End-to-end encryption secures the message", "en-krip-syen", TECHNICAL},
{"mengkompilasi", "compile", VERB, "Menerjemahkan kode sumber", "The system is compiling the code", "kem-pail", TECHNICAL},
{"variabel", "variable", NOUN, "Penyimpan nilai yang dapat berubah", "Declare the variable before using it", "ve-ri-e-bel", TECHNICAL},
{"basisdata", "database", NOUN, "Kumpulan data yang terorganisir", "This system is connected to the database", "dei-ta-beis", TECHNICAL},
{"menginisialisasi", "initialize", VERB, "Memberikan nilai awal", "Make sure to initialize the pointer with NULL", "i-ni-syye-lais", TECHNICAL},
{"sintaksis", "syntax", NOUN, "Aturan penulisan kode", "There is a syntax error on line 10", "sin-teks", TECHNICAL},
{"kompilator", "compiler", NOUN, "Program penerjemah kode", "The GCC compiler rejected your code", "kem-pai-ler", TECHNICAL},
{"rekursi", "recursion", NOUN, "Fungsi yang memanggil dirinya sendiri", "A recursion function needs a clear base case", "ri-ker-jyen", TECHNICAL},
{"antrean", "queue", NOUN, "Struktur data berprinsip FIFO", "The new element is inserted at the back of the queue", "kyuu", TECHNICAL},
{"tumpukan", "stack", NOUN, "Struktur data berprinsip LIFO", "The undo feature uses a stack structure", "stek", TECHNICAL},
{"simpul", "node", NOUN, "Titik dasar dalam struktur data berantai", "Each node stores a value and a reference", "noud", TECHNICAL},
{"antarmuka", "interface", NOUN, "Titik interaksi antara sistem dan pengguna", "The application interface is made interactive", "in-ter-feis", TECHNICAL},
{"galat", "error", NOUN, "Kondisi tidak normal dalam eksekusi program", "The compiler found an error in the code logic", "e-rer", TECHNICAL},
{"iterasi", "iteration", NOUN, "Perulangan eksekusi dalam blok kode", "The search process finishes at the third iteration", "i-te-rei-syen", TECHNICAL},
{"pengawakutuan", "debugging", NOUN, "Proses mencari dan memperbaiki kesalahan kode", "We will do some debugging tonight", "di-ba-ging", TECHNICAL},
{"penunjuk", "pointer", NOUN, "Variabel yang menyimpan alamat memori", "Be careful when freeing memory on a pointer", "poin-ter", TECHNICAL},
{"larik", "array", NOUN, "Struktur data yang menyimpan elemen bertipe sama", "Use an array to store sequential data", "e-rei", TECHNICAL},
{"klien", "client", NOUN, "Aplikasi yang meminta layanan", "The client sends a request to the server", "klai-ent", TECHNICAL},
{"peladen", "server", NOUN, "Sistem komputer yang menyediakan layanan", "The server is experiencing a temporary outage", "ser-ver", TECHNICAL},
{"kueri", "query", NOUN, "Permintaan spesifik ke dalam basis data", "This query runs very slowly", "kwi-ri", TECHNICAL},
{"asinkron", "asynchronous", ADJECTIVE, "Proses yang berjalan tanpa harus saling menunggu", "The data fetching is done asynchronously", "e-sin-kre-nes", TECHNICAL},
{"kerangka", "framework", NOUN, "Struktur konseptual untuk membangun perangkat lunak", "We are using a new framework", "freim-werk", TECHNICAL},
{"objek", "object", NOUN, "Instansi dari sebuah kelas dalam pemrograman", "We need to create a new object to manage this function", "ob-jekt", TECHNICAL},
{"kelas", "class", NOUN, "Cetak biru untuk menciptakan objek", "Declare all properties inside the main class", "klees", TECHNICAL},
{"enkapsulasi", "encapsulation", NOUN, "Pembungkusan data untuk menyembunyikan detail", "Encapsulation prevents variables from being changed carelessly", "en-kep-su-lei-syen", TECHNICAL},
{"skrip", "script", NOUN, "Rangkaian instruksi program kecil", "This script was written specifically to clean data", "skript", TECHNICAL},
{"transparansi", "transparency", NOUN, "Sifat visual yang tembus pandang", "The transparency effect makes the UI look more modern", "trens-pe-ren-si", TECHNICAL},
{"pengalaman", "experience", NOUN, "Interaksi pengguna terhadap sebuah product", "Our main focus is to improve the user experience", "ek-spi-ri-ens", TECHNICAL},
{"estetika", "aesthetics", NOUN, "Cabang filsafat yang menelaah keindahan", "The aesthetics of glassmorphism design are very pleasing to the eye", "es-the-tiks", TECHNICAL},
{"batasan", "limit", NOUN, "Nilai yang didekati oleh suatu fungsi", "Make sure not to exceed the memory limit on the system", "li-mit", TECHNICAL},
{"matriks", "matrix", NOUN, "Susunan angka dalam baris dan kolom", "This matrix multiplication operation runs quite slowly", "mei-triks", TECHNICAL},
{"turunan", "derivative", NOUN, "Laju perubahan suatu fungsi", "We must find the derivative value of this function", "di-ri-ve-tif", TECHNICAL},
{"kuantifikasi", "quantification", NOUN, "Pembatasan nilai kebenaran suatu pernyataan", "Logical quantification simplifies mathematical proofs", "kwon-ti-fi-kei-syen", TECHNICAL},
{"piksel", "pixel", NOUN, "Elemen gambar terkecil pada layar", "Apply a blur effect of ten pixels", "pik-sel", TECHNICAL},
{"autentikasi", "authentication", NOUN, "Proses validasi identitas sistem", "The OAuth2 authentication system has been successfully integrated", "o-then-ti-kei-syen", TECHNICAL},
{"metode", "method", NOUN, "Cara sistematis untuk menyelesaikan masalah", "The Gauss-Seidel numerical method needs many iterations", "me-thetd", TECHNICAL},
{"elemen", "element", NOUN, "Bagian dasar penyusun dokumen web", "This HTML element is designed to look satisfying", "e-le-ment", TECHNICAL},
{"transisi", "transition", NOUN, "Perubahan halus dari satu keadaan ke lainnya", "The transition of this glass effect is set for two seconds", "tren-zi-syen", TECHNICAL},
{"lancar", "smooth", ADJECTIVE, "Berjalan tanpa hambatan atau jeda", "The user experience on this application feels very smooth", "smuuth", TECHNICAL},
{"graf", "graph", NOUN, "Struktur data berupa kumpulan simpul dan sisi", "The shortest path search algorithm uses a graph", "gref", TECHNICAL},
{"akar", "root", NOUN, "Simpul paling atas dalam struktur pohon", "The current pointer points to the root of the BST", "ruut", TECHNICAL},
{"daun", "leaf", NOUN, "Simpul yang tidak memiliki turunan dalam pohon", "The deletion operation is easier if the node is a leaf", "liif", TECHNICAL},
{"sinkron", "synchronous", ADJECTIVE, "Proses yang berjalan berurutan saling menunggu", "This execution function call is synchronous", "sin-kre-nes", TECHNICAL},
{"berkas", "file", NOUN, "Kumpulan data yang disimpan dalam sistem", "The function to save static files has been called", "fail", TECHNICAL},
{"direktori", "directory", NOUN, "Struktur folder untuk mengorganisir berkas", "The header files must be placed inside the src directory", "dai-rek-to-ri", TECHNICAL},
{"biner", "binary", NOUN, "Sistem bilangan berbasis dua", "Computers basically only read binary code", "bai-ne-ri", TECHNICAL},
{"oktal", "octal", NOUN, "Sistem bilangan berbasis delapan", "Convert that decimal value into octal", "ok-tel", TECHNICAL},
{"heksadesimal", "hexadecimal", NOUN, "Sistem bilangan berbasis enam belas", "The interface color is represented in hexadecimal code", "hek-se-de-si-mel", TECHNICAL},
{"dekripsi", "decryption", NOUN, "Proses mengembalikan data tersembunyi ke bentuk asli", "A private key is required for the decryption process", "di-krip-syen", TECHNICAL},
{"latensi", "latency", NOUN, "Waktu tunda dalam pengiriman data", "The server in this region has very low latency", "lei-ten-si", TECHNICAL},
{"proksi", "proxy", NOUN, "Perantara yang meneruskan permintaan pengguna", "We need to configure the proxy to access the server", "prok-si", TECHNICAL},
{"modul", "module", NOUN, "Bagian program yang terpisah dapat berintegrasi", "The data structure module has been compiled separately", "mo-dyuul", TECHNICAL},
{"parameter", "parameter", NOUN, "Variabel yang diterima oleh suatu fungsi", "The add word function requires a parameter of struct type", "pe-re-mi-ter", TECHNICAL},
{"argumen", "argument", NOUN, "Nilai yang dikirimkan ke dalam sebuah fungsi", "Make sure the argument data type matches the declaration", "ar-gyu-ment", TECHNICAL},
{"peramban", "browser", NOUN, "Perangkat lunak untuk mengakses internet", "The extension can only be installed on Chromium-based browsers", "brau-zer", TECHNICAL},
{"utas", "thread", NOUN, "Proses eksekusi tunggal dari sebuah program", "Use multi-threading to speed up data processing", "thred", TECHNICAL},
{"prosesor", "processor", NOUN, "Sirkuit utama yang menjalankan instruksi", "The latest generation processor is more power efficient", "pro-se-ser", TECHNICAL},
{"arsitektur", "architecture", NOUN, "Rancangan dasar dari sebuah sistem", "A client-server architecture is used for this application", "aar-ki-tek-cer", TECHNICAL},
{"partisi", "partition", NOUN, "Pembagian ruang penyimpanan memori", "Reformat the partition before installing the operating system", "par-ti-syen", TECHNICAL},
{"protokol", "protocol", NOUN, "Aturan baku untuk komunikasi jaringan", "The HTTP protocol ensures long-distance text transfer", "prou-to-kol", TECHNICAL},
{"pita", "band", NOUN, "Rentang frekuensi dalam komunikasi", "The bandwidth of this connection is very small", "bend", TECHNICAL},
{"topologi", "topology", NOUN, "Struktur dari suatu jaringan", "The star topology centralizes connections on one server", "te-po-le-ji", TECHNICAL},
{"domain", "domain", NOUN, "Nama unik pengenal alamat IP di internet", "The domain name of this application must be registered", "dou-mein", TECHNICAL},
{"hos", "host", NOUN, "Komputer yang terhubung ke jaringan", "Local host is used to test the server from one's own computer", "houst", TECHNICAL},
{"hipertaut", "hyperlink", NOUN, "Referensi navigasi ke dokumen lain", "Click the hyperlink to open the API guide", "hai-per-lingk", TECHNICAL},
{"navigasi", "navigation", NOUN, "Sistem perpindahan antar halaman web", "The navigation bar is designed using glassmorphism", "ne-vi-gei-syen", TECHNICAL},
{"resolusi", "resolution", NOUN, "Kerapatan piksel pada sebuah layar", "The image will break if the screen has a high resolution", "re-zo-lu-syen", TECHNICAL},
{"animasi", "animation", NOUN, "Simulasi gerakan berurutan", "The status change animation runs smoothly", "e-ni-mei-syen", TECHNICAL},
{"portabilitas", "portability", NOUN, "Kemampuan perangkat lunak dijalankan di berbagai sistem", "The C language is famous for its high portability", "por-te-bi-li-ti", TECHNICAL},
{"reliabilitas", "reliability", NOUN, "Tingkat keandalan sebuah sistem", "The reliability of this trie search function is very stable", "ri-lai-e-bi-li-ti", TECHNICAL},
{"skalabilitas", "scalability", NOUN, "Kemampuan sistem menangani lonjakan data", "The use of hash tables greatly supports application scalability", "skei-le-bi-li-ti", TECHNICAL},
{"kriptografi", "cryptography", NOUN, "Ilmu penyandian data digital", "Modern cryptography methods are very difficult to hack", "krip-tog-re-fi", TECHNICAL},
{"polimorfisme", "polymorphism", NOUN, "Konsep kemampuan objek memiliki banyak bentuk", "Although uncommon in C, polymorphism can be simulated with pointers", "po-li-mor-fi-zem", TECHNICAL},
{"pewarisan", "inheritance", NOUN, "Penurunan sifat dari kelas induk ke anak", "Property inheritance reduces code duplication in the program", "in-he-ri-tens", TECHNICAL},
{"abstraksi", "abstraction", NOUN, "Proses menyembuyenkan kerumitan implementasi", "The abstraction layer is used so users can focus on features", "eb-strek-syen", TECHNICAL},
{"kompresi", "compression", NOUN, "Pengecilan ukuran data digital", "The compression algorithm saves space in the tree structure", "kem-pre-syen", TECHNICAL},
{"repositori", "repository", NOUN, "Tempat penyimpanan sentral dari kode program", "Don't forget to upload these code changes to the repository", "ri-poz-i-to-ri", TECHNICAL},
{"komit", "commit", VERB, "Menyimpan rekam jejak perubahan dalam sistem versi", "The commit message must clearly describe the changes made", "ke-mit", TECHNICAL},
{"cabang", "branch", NOUN, "Jalur pengembangan terpisah dalam repositori", "Please create a new branch before changing the linked list logic", "brenc", TECHNICAL},
{"terminal", "terminal", NOUN, "Antarmuka berbasis teks untuk sistem operasi", "Run the GCC compilation command through the terminal", "ter-mi-nel", TECHNICAL},
{"konsol", "console", NOUN, "Panel kontrol atau antarmuka baris perintah", "This dictionary program runs entirely on the console", "ken-soul", TECHNICAL},
{"pustaka", "library", NOUN, "Kumpulan kode yang dapat digunakan ulang", "The C standard library provides memory allocation functions", "lai-bre-ri", TECHNICAL},
{"kerentanan", "vulnerability", NOUN, "Celah keamanan pada suatu sistem", "A vulnerability in the input function can be exploited by hackers", "vel-ne-re-bi-li-ti", TECHNICAL},
{"peretasan", "hacking", NOUN, "Tindakan eksploitasi sistem komputer", "The bank system just experienced hacking", "he-king", TECHNICAL},
{"bita", "byte", NOUN, "Satuan informasi digital sebesar delapan bit", "The maximum size for a file name is 255 bytes", "bait", TECHNICAL},
{"prasyarat", "prerequisite", NOUN, "Syarat dasar sebelum melakukan sesuatu", "Data structures are a prerequisite for this course", "pri-re-kwi-zit", TECHNICAL},
{"semantik", "semantics", NOUN, "Makna dari suatu kode atau bahasa", "Semantically, this HTML structure is already correct", "si-men-tiks", TECHNICAL},
{"leksikal", "lexical", ADJECTIVE, "Berkaitan dengan kata atau kosa kata dalam bahasa", "The compiler is performing a lexical analysis on the code", "lek-si-kel", TECHNICAL},
{"dependensi", "dependency", NOUN, "Ketergantungan program terhadap pustaka lain", "All project dependencies must be installed first", "di-pen-den-si", TECHNICAL}
    };

    int count = sizeof(initial_words) / sizeof(initial_words[0]);

    for (int i = 0; i < count; i++) {
        WordEntry entry = create_word_entry(
            initial_words[i].indonesian,
            initial_words[i].english,
            initial_words[i].pos,
            initial_words[i].definition,
            initial_words[i].example,
            initial_words[i].pronunciation,
            initial_words[i].category
        );

        dict_add_word(dict, entry);
    }

    // Reset undo stack agar tidak menyimpan 300 kata saat startup
    dict->undo_stack->top = -1;
}